### ISSUE TITLE
Расположение программ

### ISSUE THREAD

**Issue by vnebelunka** [d-uni/uni#2]
реализация функций СИ должна быть вынесена в отдельный файл, как и тестирование.

**Comment by d-uni** [comment]
Обязательно?

**Comment by d-uni** [comment]
Вроде бы у нас все сдавали в одном файле ..\.\

**Comment by vnebelunka** [comment]
нормальные люди так не делают

**Comment by d-uni** [comment]
я знаю ,,,, но это же должно работать

**Comment by vnebelunka** [comment]
а я же не говорю, что ломается на этом))

**Comment by d-uni** [comment]
хорошо,,, я могу переделать,, но мне пока важно ,, что бы просто работало ,,, потому что мне нужно будет просто запустить прогу и все(())
